- name: PackageInstall
  hosts: all
  become: true
  become_user: root

  vars_files:
    - ./packages.txt

  vars:
    docker_repo_uri: "https://download.docker.com/linux/debian"
    docker_keyring_path: "/etc/apt/keyrings/docker.asc"
    docker_sources_path: "/etc/apt/sources.list.d/docker.sources"
    extra_path: "/home/ansible/cmake-4.2.0-linux-x86_64/bin"

  tasks:
    - name: Ensure required dependencies for Docker repo are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: "{{ docker_repo_uri }}/gpg"
        dest: "{{ docker_keyring_path }}"
        mode: "0644"

    - name: Configure Docker repository
      ansible.builtin.copy:
        dest: "{{ docker_sources_path }}"
        mode: "0644"
        content: |
          Types: deb
          URIs: {{ docker_repo_uri }}
          Suites: {{ ansible_lsb.codename | default(ansible_facts.distribution_release) }}
          Components: stable
          Signed-By: {{ docker_keyring_path }}

    - name: Update APT cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: true

    - name: Ensure packages (from packages.txt) are installed
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

    - name: Install CMake 4.2
      become: true
      become_user: ansible
      ansible.builtin.get_url:
        url: https://github.com/Kitware/CMake/releases/download/v4.2.0/cmake-4.2.0-linux-x86_64.tar.gz
        dest: /home/ansible/cmake.tar.gz
        mode: '0440'

    - name: Unpack CMake
      become: true
      become_user: ansible
      ansible.builtin.unarchive:
        src: /home/ansible/cmake.tar.gz
        dest: /home/ansible
        remote_src: true

    - name: Add CMake to PATH
      become: true
      become_user: root
      ansible.builtin.copy:
        content: "export PATH=$PATH:{{ extra_path }}"
        dest: "/etc/profile.d/cmakePath.sh"
        owner: root
        group: root
        mode: "0644"
        remote_src: true
