- name: AnsibleUserCreation
  import_playbook: playbooks/useradd-Ansible.yml
  tags: useradd

- name: PKGinstall
  import_playbook: playbooks/install.yml
  tags: pkginstall

- name: Webconfig
  import_playbook: playbooks/webConfig.yml
  tags: webconfig

- name: TTTdbsetup
  import_playbook: playbooks/tttDBsetup.yml
  tags: tttdbsetup

- name: TTTdeploy
  import_playbook: playbooks/deployTTT.yml
  tags: tttdeploy

- name: NPMdeploy
  import_playbook: playbooks/reverseproxySetup.yml
  tags: revproxy
